[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
plotters = "0.3.1"
rayon = "1.10.0"
num_cpus= "1.16.0"
egui = "0.22.0"
egui-plotter = "0.3.0"
eframe = "0.22.0"
winapi = { version = "0.3.9", features = ["winuser"] }


